<a href="https://colab.research.google.com/github/Rhythmbellic/TF_bellic_robotics/blob/main/Basic_tensors_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [89]:
import tensorflow as tf

# Creating random tensors
Random tensors are tensors of some abitrary size which contain random numbers.

In [93]:
# Create a random generator with a non-deterministic seed
random_gen = tf.random.Generator.from_non_deterministic_state()

# Generate a tensor from a normal distribution
random_tensor = random_gen.normal(shape=(3, 2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.8298724 , -2.0110428 ],
       [ 0.09552014,  0.8078356 ],
       [-1.3998997 , -0.365842  ]], dtype=float32)>

In [100]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(23) # set the seed for reproducibility
tensor_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution
tensor_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.1175475 ,  0.03493892],
       [-1.5700307 ,  0.4457582 ],
       [ 0.10944034, -0.8035768 ]], dtype=float32)>

In [105]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
tensor_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution
random_2 = tf.random.Generator.from_seed(42)
tensor_2 = random_2.normal(shape=(3, 2))

# explaination
tf.random.Generator.from_seed(42) creates a deterministic random number generator. Every time you use it with the same seed, it will generate the same sequence of random numbers.

.normal(shape=(3, 2)) tells the generator to draw numbers from a standard normal distribution (mean = 0, stddev = 1) in the shape (3, 2).

In [104]:
# Are they equal?
tensor_1 == tensor_2

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [106]:
# Create two random (and different) tensors
random_3 = tf.random.Generator.from_seed(42)
tensor_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
tensor_4 = random_4.normal(shape=(3, 2))

In [107]:
tensor_1 == tensor_3

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [108]:
tensor_3 == tensor_4

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [116]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [121]:
# Shuffle in the same order every time using the seed parameter (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [141]:
# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=12)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [134]:
# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

# Other ways to make tensors

In [144]:

# Make a tensor of all ones
tf.ones(shape=(3, 5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [146]:
# Make a tensor of all zeros
tf.zeros(shape=(4, 2,5,9))

<tf.Tensor: shape=(4, 2, 5, 9), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]

In [147]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,
                shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

In [148]:
import numpy as np

In [149]:
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25

In [150]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [152]:
A = tf.constant(numpy_A,
                shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array

In [153]:
A

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)>