<a href="https://colab.research.google.com/github/Rhythmbellic/TF_bellic_robotics/blob/main/TENSORS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##CONTENT OF THE VIDEO



*   Basic concept of colab
*   creating a tensor using tf.constant
*   create a tensor using tf.variable







In [2]:
#import tensorflow
import tensorflow as tf
tf.__version__

'2.18.0'

In [3]:
#creting tensor with tf.constant
scalar=tf.constant(69)
print(scalar)
scalar.ndim

tf.Tensor(69, shape=(), dtype=int32)


0

In [4]:
vector=tf.constant([8,9])
print(vector)
vector.ndim

tf.Tensor([8 9], shape=(2,), dtype=int32)


1

In [5]:
matrix=tf.constant([[2,3],[2,3]])
print(matrix)
matrix.ndim

tf.Tensor(
[[2 3]
 [2 3]], shape=(2, 2), dtype=int32)


2

In [6]:
ten=tf.constant([[[69,45],[45,55]],
                 [[55,66],[69,96]]])
print(ten)
ten.ndim

tf.Tensor(
[[[69 45]
  [45 55]]

 [[55 66]
  [69 96]]], shape=(2, 2, 2), dtype=int32)


3

In [7]:
vector.assign([5,9])

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [8]:
vector_1=tf.Variable([56,89])

In [9]:
vector_1.assign([5,9])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>

In [10]:
vector_1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>