<a href="https://colab.research.google.com/github/Rhythmbellic/TF_bellic_robotics/blob/main/Tensors_manipulation_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
import tensorflow as tf
import numpy as np


# Changing the datatype of a tensor

In [77]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

In [78]:
# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [79]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B


<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [80]:
# Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

# **Getting the absolute value**

tf.abs()

In [81]:
# Create tensor with negative values
D = tf.constant([-7, -10])
D


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [82]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

# Finding the min, max, mean, sum (aggregation)



---



tf.reduce_min() - find the minimum value in a tensor.

tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).

tf.reduce_mean() - find the mean of all elements in a tensor.

tf.reduce_sum() - find the sum of all elements in a tensor.


In [83]:
# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([83, 74, 35, 17, 82, 33, 90, 44, 96, 92, 67, 52, 95, 42, 87, 92, 36,
        8, 23, 30, 75, 52, 94,  1, 98, 95, 66, 58, 17, 10, 40, 64, 78, 45,
        0, 24, 43, 52, 35, 75, 39, 64, 32, 50, 71, 67, 32, 32, 38,  1])>

In [84]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [85]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [86]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [87]:

# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2626>

# Finding the positional maximum and minimum


---
tf.argmax() - find the position of the maximum element in a given tensor.

tf.argmin() - find the position of the minimum element in a given tensor.


In [89]:
# Create a tensor with 50 values between 0 and 1
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.00870077, 0.69314669, 0.89618426, 0.63253005, 0.68387173,
       0.89097614, 0.35775429, 0.04889212, 0.78850976, 0.9406399 ,
       0.10842415, 0.00761111, 0.95766736, 0.6913512 , 0.58981614,
       0.23997108, 0.45250732, 0.2785664 , 0.7217528 , 0.44323944,
       0.64475034, 0.50970885, 0.06991244, 0.31114292, 0.67208697,
       0.28280798, 0.5897036 , 0.15506209, 0.81930279, 0.16406114,
       0.60703861, 0.78145849, 0.58094179, 0.08382023, 0.67268083,
       0.34178063, 0.22698553, 0.98895374, 0.21387582, 0.29749506,
       0.63219889, 0.23090043, 0.40154664, 0.89441188, 0.69305642,
       0.7657576 , 0.50809948, 0.06974201, 0.53428188, 0.74212137])>

In [91]:
# Find the maximum element position of F
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=37>

In [90]:

# Find the minimum element position of F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=11>

In [92]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}")
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 37
The maximum value of F is: 0.9889537369056404


Squeezing a tensor (removing all single dimensions)


---


If you need to remove single-dimensions from a tensor (dimensions with size 1), you can use tf.squeeze().

tf.squeeze() - remove all dimensions of 1 from a tensor.


In [93]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim


(TensorShape([1, 1, 1, 1, 50]), 5)

In [94]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

# Squaring, log, square root


---

tf.square() - get the square of every value in a tensor.

tf.sqrt() - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).

tf.math.log() - get the natural log of every value in a tensor (elements need to floats).

In [95]:
# Create a new tensor
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [96]:

# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [97]:

# Find the squareroot (will error), needs to be non-integer
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int64 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [98]:
# Change H to float32
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [99]:
# Find the square root
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [100]:

# Find the log (input also needs to be float)
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Manipulating tf.Variable tensors


---
.assign() - assign a different value to a particular index of a variable tensor.

.add_assign() - add to an existing value and reassign it at a particular index of a variable tensor.


In [101]:
# Create a variable tensor
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [102]:
# Assign the final value a new value of 50
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [103]:
# The change happens in place (the last value is now 50, not 4)
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [104]:
# Add 10 to every element in I
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [105]:
# Again, the change happens in place
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

# Tensors and NumPy



---

np.array() - pass a tensor to convert to an ndarray (NumPy's main datatype).

tensor.numpy() - call on a tensor to convert to an ndarray.


In [106]:

# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [107]:
# Convert tensor J to NumPy with np.array()
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [108]:
# Convert tensor J to NumPy with .numpy()
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [109]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# Using @tf.function

In [110]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [111]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>